Repository DEFRA/water-abstraction-tactical-idm, pull requests merged in 2022-08, with the labels that each got.

#794 Update release process
  package.json
Labels: enhancement

#795 Hide `standard` linting commit with `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: enhancement, housekeeping

#796 Set log level using new env var
  .env.example
  config.js
  test/config.js
Labels: housekeeping

#798 Correctly set NODE_ENV
  .env.example
  config.js
  src/modules/acceptance-tests/controller.js
  src/modules/acceptance-tests/routes.js
Labels: housekeeping
